DROP TABLE public.empleados CASCADE;
DROP TABLE public.clientes CASCADE;
DROP TABLE public.despachadores CASCADE;
DROP TABLE public.categoria CASCADE;
DROP TABLE public.proveedores CASCADE;
DROP TABLE public.productos CASCADE;
DROP TABLE public.compras CASCADE;
DROP TABLE public.orden_de_compra CASCADE;
DROP TABLE public.ordenes CASCADE;